services:
  frontend:
    build: .
    container_name: frontend-boti
    ports:
      - '8501:8501'
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - supabase_network_orchestrator-boti

networks:
  supabase_network_orchestrator-boti:
    name: supabase_network_orchestrator-boti
    external: true